tags:
  - name: user
    description: User documentation
  - name: upload
    description: Upload documentation
  - name: exchangeRate
    description: token price
  - name: apikey
    description: api key
  - name: invoice
    description: invoice - one kind of charge
security:
  - bearerAuth: []
paths:
  ## User tag
  # [POST] user
  /user/register:
    post:
      tags:
        - user
      summary: User register
      parameters:
        - name: body
          in: body
          description: User data
          required: true
          schema:
            $ref: '#/definitions/user'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  # [PUT] resend verify email
  /user/resend:
    put:
      tags:
        - user
      summary: User resend verify email
      parameters:
        - name: account
          in: query
          description: Email
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  # [PUT] active user
  /user/active:
    put:
      tags:
        - user
      summary: User active account
      parameters:
        - name: account
          in: query
          description: Email
          required: true
          type: string
        - name: activeCode
          in: query
          description: Active code
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [POST] Login with auth code
  /user/login:
    post:
      tags:
        - user
      summary: Login with auth code
      parameters:
        - name: body
          in: body
          description: Login data
          required: true
          schema:
            $ref: '#/definitions/login'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [PUT] generate qr for two factor authentication
  /user/generate-qr:
    put:
      tags:
        - user
      summary: User generate qr for scan
      parameters:
        - name: Authorization
          in: header
          description: an authorization header
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [PUT] enable two factor authentication
  /user/enable-2fa:
    put:
      tags:
        - user
      summary: Enable two factor authentication
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [PUT] Send a code 6 digests to email
  /user/forgot-password:
    put:
      tags:
        - user
      summary: Send a code 6 digests to email
      parameters:
        - name: email
          in: body
          description: Email
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [PUT] Change password
  /user/change-password:
    put:
      tags:
        - user
      summary: Change password with 6 digests
      parameters:
        - name: email
          in: body
          description: Email
          required: true
          type: string
        - name: newPassword
          in: body
          description: New password
          required: true
          type: string
        - name: forgotPassCode
          in: body
          description: 6 digests sent to email
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  ## ExchangeRate tag
  # [GET-POST] fiat-to-crypto
  /fiat-to-crypto:
    get:
      tags:
        - exchangeRate
      summary: fiat-to-crypto converter
      parameters:
        - name: localCurrency
          in: query
          description: localCurrency data
          required: true
        - name: amount
          in: query
          description: amount data
          required: true
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
        - exchangeRate
      summary: fiat-to-crypto setup token active/inactive
      parameters:
        - name: body
          in: body
          description: exchange data
          required: true
          schema:
            $ref: '#/definitions/exchange'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  ## ApiKey
  # [GET] generate new api key
  /apikey/new:
    get:
      tags:
        - apikey
      summary: generate new api key
      parameters:
        - name: Authorization
          in: header
          description: an authorization header
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [DELETE] remove api key
  /apikey/{apikey}:
    delete:
      tags:
        - apikey
      summary: delete api key
      parameters:
        - name: Authorization
          in: header
          description: an authorization header
          required: true
          type: string
        - name: apikey
          in: path
          description: api key string length 20
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  ## Invoice
  # [POST] create a voice
  /invoices:
    post:
      tags:
        - invoice
      summary: create a voice
      parameters:
        - name: Authorization
          in: header
          description: an authorization header
          required: true
          type: string
        - name: body
          in: body
          description: invoice data
          required: true
          schema:
            $ref: '#/definitions/invoice'
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    get:
      tags:
        - invoice
      summary: get list invoices
      parameters:
        - name: Authorization
          in: header
          description: an authorization header
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  # [GET] get a invoice by code
  /charges/{code}:
    get:
      tags:
        - invoice
      summary: get a invoice by code
      parameters:
        - name: Authorization
          in: header
          description: an authorization header
          required: true
          type: string
        - name: code
          in: path
          description: code string length 12
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  ## File tag
  # [POST] File
  /upload/single:
    post:
      tags:
        - upload
      consumes:
        - multipart/form-data
      summary: Upload single file
      parameters:
        - name: file
          in: formData
          description: File data
          required: true
          type: file
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

  /upload/multiple:
    post:
      tags:
        - upload
      consumes:
        - multipart/form-data
      summary: Upload multiple files
      parameters:
        - name: files
          in: formData
          description: Multiple files data
          required: true
          type: array
          items:
            type: file
          # collectionFormat: multi
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  ##static
  #[GET] file
  /static/{path}:
    get:
      tags:
        - static
      # consumes:
      #   - multipart/form-data
      summary: Get file
      parameters:
        - name: path
          in: path
          description: Response
          required: true
      produces:
        - image/png
        - image/gif
        - image/jpeg
      responses:
        200:
          description: 'OK'
          schema:
            type: file
        500:
          description: 'Server Error'

    # [PUT] resend verify email

# definitions
definitions:
  user:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password
  exchange:
    type: object
    required:
      - symbol
      - status
    properties:
      symbol:
        type: string
        description: symbol of token
      status:
        type: string
        description: enum["active", "inactive"]
  login:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password
      twofaCode:
        type: string
        description: Two factor authentication
  invoice:
    type: object
    required:
      - email
      - currencyType
      - currency
      - amount
    properties:
      email:
        type: string
        description: User email
      currencyType:
        type: string
        description: currencyType LOCAL_CURRENCY/CRYPTO_CURRENCY
      currency:
        type: string
        description: currency symbol
      amount:
        type: number
        description: amount
      name:
        type: string
        description: name
      memo:
        type: string
        description: memo
schemes:
  - https
  - http

securityDefinitions:
  Authorization:
    type: apiKey
    name: Authorization
    in: header
    scheme: bearer
