export enum CurrentStepEnum {
  REGISTERED = 'REGISTERED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  SETUP_2FA_COMPLETED = 'SETUP_2FA_COMPLETED',
  SETUP_WALLET_COMPLETED = 'SETUP_WALLET_COMPLETED',
  VERIFIED = 'VERIFIED',
}
